/** Major Indian banks — public, private, small finance, payments, and select co-operative */
export const INDIAN_BANKS = [
  "Abhyudaya Co-operative Bank",
  "Airtel Payments Bank",
  "AU Small Finance Bank",
  "Axis Bank",
  "Bandhan Bank",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Barclays Bank",
  "BNP Paribas",
  "Canara Bank",
  "Capital Small Finance Bank",
  "Central Bank of India",
  "Citibank",
  "City Union Bank",
  "Cosmos Co-operative Bank",
  "CSB Bank",
  "DBS Bank",
  "DCB Bank",
  "Deutsche Bank",
  "Dhanlaxmi Bank",
  "Equitas Small Finance Bank",
  "ESAF Small Finance Bank",
  "Federal Bank",
  "Fincare Small Finance Bank",
  "Fino Payments Bank",
  "HDFC Bank",
  "HSBC",
  "ICICI Bank",
  "IDBI Bank",
  "IDFC FIRST Bank",
  "India Post Payments Bank",
  "Indian Bank",
  "Indian Overseas Bank",
  "IndusInd Bank",
  "Jammu & Kashmir Bank",
  "Jana Small Finance Bank",
  "Jio Payments Bank",
  "Karnataka Bank",
  "Karur Vysya Bank",
  "Kotak Mahindra Bank",
  "Nainital Bank",
  "NKGSB Co-operative Bank",
  "North East Small Finance Bank",
  "NSDL Payments Bank",
  "Paytm Payments Bank",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "RBL Bank",
  "Saraswat Co-operative Bank",
  "Shivalik Small Finance Bank",
  "South Indian Bank",
  "Standard Chartered Bank",
  "State Bank of India",
  "Suryoday Small Finance Bank",
  "Tamilnad Mercantile Bank",
  "TJSB Sahakari Bank",
  "UCO Bank",
  "Ujjivan Small Finance Bank",
  "Union Bank of India",
  "Unity Small Finance Bank",
  "Utkarsh Small Finance Bank",
  "Yes Bank",
] as const;

export type IndianBank = (typeof INDIAN_BANKS)[number];

export function filterIndianBanks(query: string): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...INDIAN_BANKS];
  return INDIAN_BANKS.filter((bank) => bank.toLowerCase().includes(q));
}
